name: "PR Testing"

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node v16
        uses: actions/setup-node@v1
        with:
          node-version: "16.0"
      - run: yarn
      - run: yarn test
